### ISSUE TITLE
Unable de download administration app

### ISSUE THREAD

**Issue by lduparc** [googlesamples/android-NfcProvisioning#1]
Using this sample app with the deviceOwner app installed on the master device, the child device is encrypted and started on Android for Work setup page but it is not able to download the administration app to the child device. 

I'm using a Motorola X Style (XT1572) on Android 6.0 for my tests.
Do I have to define a specific configuration in order to be able to download the admin app ?

Properties are the following : 

```
DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_NAME,
                "com.example.androidmdm");
DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION,
                "https://drive.google.com/file/d/XXXXXXXXXXX/view?usp=sharing");
DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM,
                "base64 and sha-256 EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION");
```

**Comment by saddahussain** [comment]
You have to provide a downloadable url.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
