### ISSUE TITLE
Why PACKAGE DOWNLOAD LOCATION is nothing?

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-NfcProvisioning#2]
Why this sample don't contain EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION?
It seems require.

Document says
"A String extra holding a url that specifies the download location of the device admin package. When not provided it is assumed that the device admin package is already installed"
REF:
https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html

But, We must do factory reset to enable DeviceOwner feature, therefore, device don't have admin package.

**Comment by rsviolin** [comment]
I have the same problem.

**Comment by KunYi** [comment]
check the below information about "nfcprovisioning.txt" file
https://developer.android.com/work/guide#provision-a-device-owner

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
